### ISSUE TITLE
NPE in resize()

### ISSUE THREAD

**Issue by bitbionic** [kloder-games/godot-admob#10]
I'm receiving a NullPointerException in the resize() method consistently when you hit the power button to turn off the screen while the game is playing, change the orientation while the screen is off, and then try to open the screen back up and resume. I'm still debugging, but this is the stack trace from multiple devices on Google Play crash analytics that led me to investigate:

```
java.lang.NullPointerException: 
  at org.godotengine.godot.GodotAdMob$6.run (GodotAdMob.java:255)
  at android.os.Handler.handleCallback (Handler.java:739)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:148)
  at android.app.ActivityThread.main (ActivityThread.java:5480)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
```

I tried wrapping layout and adView in null checks but then the error just propagated to AdParams:
```
12-05 09:57:10.881 16524 16524 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'int android.widget.FrameLayout$LayoutParams.gravity' on a null object reference
12-05 09:57:10.881 16524 16524 E AndroidRuntime: 	at org.godotengine.godot.GodotAdMob$6.run(GodotAdMob.java:263)
12-05 09:57:10.881 16524 16524 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
12-05 09:57:10.881 16524 16524 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-05 09:57:10.881 16524 16524 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
12-05 09:57:10.881 16524 16524 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
12-05 09:57:10.881 16524 16524 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-05 09:57:10.881 16524 16524 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-05 09:57:10.881 16524 16524 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
I'm assuming I need to detect the nulls and reinitialize?

**Comment by bitbionic** [comment]
So just a follow-up - I added the following null check at the beginning of the resize() method and it seems to alleviate the issue:

```java
	public void resize()
	{
		activity.runOnUiThread(new Runnable()
		{
			@Override public void run()
			{
				if (layout == null || adView == null || adParams == null )
				{
					Log.d("BIT-BIONIC", "GodotAdMob.resize: nulls found, Activity is " + activity);
					Log.d("BIT-BIONIC", "EXITING resize()");
					return;
				}

				layout.removeView(adView); // Remove the old view
```

My application is locked in Landscape so I don't know if this will work for apps that can switch between portrait and landscape, but it doesn't seem to crash anymore here with this check.
